### ISSUE TITLE
Dont work with IP camera

### ISSUE THREAD

**Issue by indio99** [PBfordev/wxopencvtest#1]
Hi

I like your project, I think that is very interesting.

I check all options and work well as spected, but on IP Camera option, don´t work for me.

Always say "Could not connect to the camera"

I try with diferent URLs and the result is the same, I try this URLs with VLC and all work fine, the issue occur same with the default URL in your code.

I try with .mjpg termination in the URL string and the result are the same too.

do you think that are problem of my library installation? I work in windows 10, wxWidgets 3.1.5 compiled form source and opencv 4 and opencv-contrib compiled from source too.

I think that I compiled opencv with FFMPG=ON, but not completly sure.

Thanks

**Comment by PBfordev** [comment]
As you [can see in the source code](https://github.com/PBfordev/wxopencvtest/blob/main/ocvframe.cpp#L302), the error is displayed when OpenCV could not open the video capture, it is not related to my code.

To make sure, I have just built and run the demo app using prebuilt OpenCV 4.5 package both with MSVC 2019 and GCC 10.3 (from msys2). The IP camera stream for the default URL was displayed in both.

Assuming the URL is valid, my guess would be that you have invalid OpenCV build or installation. Or perhaps your firewall/antivirus somehow blocks the application access to the internet?  Did you try running [the code from OpenCV documentation](https://docs.opencv.org/4.5.3/d8/dfe/classcv_1_1VideoCapture.html) verbatim, except using an URL instead of a deviceId?

**Comment by indio99** [comment]
Hi.

Thanks for your reply.
The problem are resolved, was missed opencv_videoio_ffmpegXXX_64.dll because when I compiled opencv with cmake, cmake was can't download ffmpeg libs because my version of cmake don`t accept ssl certificates by curl inside version.

I need opencv with contrib, I downloaded a prebuilt opencv with contrib 4.1.2 for mingw and video from camera Ip work fine as espected now.

Thank you very much.
Best regards.
